[package]
name = "brix"
version = "0.1.0"
authors = ["dani"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.51"
macroquad = "0.3.7"